// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: kaiwtnufwjzhlxmcqypq

class SupabaseConfig {
  static const String supabaseUrl = 'https://kaiwtnufwjzhlxmcqypq.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthaXd0bnVmd2p6aGx4bWNxeXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NTc5MDQsImV4cCI6MjA4NTQzMzkwNH0.5pUU1qHFfJEG6JBP5srg3YGP884g6QwKWod8WUKtGyU';
}
